### ISSUE TITLE
Release v1.3.0

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-confluence#95]
- https://github.com/mattermost/mattermost-plugin-confluence/pull/92
- https://github.com/mattermost/mattermost-plugin-confluence/pull/63
- https://github.com/mattermost/mattermost-plugin-confluence/pull/62
- https://github.com/mattermost/mattermost-plugin-confluence/pull/66
- https://github.com/mattermost/mattermost-plugin-confluence/pull/65
- https://github.com/mattermost/mattermost-plugin-confluence/pull/74

**Comment by mickmister** [comment]
@hanzei I'd like to repurpose this ticket to be used for the ReactDOM effort. Releasing off of the previous release is a bit tedious, partially because that version hasn't been sync'd with the starter template isn't up-to-date in general. My plan is to release off of the master branch. Here are the significant PRs since last release. They are mostly fixes:

- https://github.com/mattermost/mattermost-plugin-confluence/pull/63
- https://github.com/mattermost/mattermost-plugin-confluence/pull/62
- https://github.com/mattermost/mattermost-plugin-confluence/pull/66
- https://github.com/mattermost/mattermost-plugin-confluence/pull/65
- https://github.com/mattermost/mattermost-plugin-confluence/pull/74

**Comment by hanzei** [comment]
Sure @mickmister

**Comment by mickmister** [comment]
Released with https://github.com/mattermost/mattermost-marketplace/pull/317
